/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查端点（存活探针，供测试与运维验证服务可用）。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Entities
         * @description 检索实体（GET /api/entities?q=&type=，@ 实体选择器数据源）。
         *
         *     作用: 参数解析 + 调用 service；q 匹配名称/别名，type 过滤类型。
         *     参数: q — 关键字（空返回全量）；type — 实体类型（可选）；session — 请求级会话。
         *     返回值: list[EntityBrief]。异常: 由全局异常处理器统一出口。
         *     依赖: app.entities.service。
         */
        get: operations["search_entities_api_entities_get"];
        put?: never;
        /**
         * Create Entity
         * @description 创建实体（POST /api/entities）。
         *
         *     作用: 参数解析 + 调用 service；id 由系统生成并随响应返回。
         *     参数: payload — 创建载荷；session — 请求级数据库会话（依赖注入）。
         *     返回值: EntityRead（201）。异常: 由全局异常处理器统一出口。
         *     依赖: app.entities.service。
         */
        post: operations["create_entity_api_entities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity
         * @description 查询实体详情（GET /api/entities/{id}）。
         *
         *     作用: 参数解析 + 调用 service。
         *     参数: entity_id — 路径参数实体 id；session — 请求级数据库会话。
         *     返回值: EntityRead。异常: 404 由全局异常处理器统一出口。
         *     依赖: app.entities.service。
         */
        get: operations["get_entity_api_entities__entity_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Entity
         * @description 删除实体（DELETE /api/entities/{id}；被引用时 409 阻断）。
         *
         *     作用: 参数解析 + 调用 service。
         *     参数: entity_id — 路径参数实体 id；session — 请求级数据库会话。
         *     返回值: 无（204）。异常: 404/409 由全局异常处理器统一出口。
         *     依赖: app.entities.service。
         */
        delete: operations["delete_entity_api_entities__entity_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Entity
         * @description 局部更新实体（PATCH /api/entities/{id}；id 不可变）。
         *
         *     作用: 参数解析 + 调用 service；仅更新显式提供的字段。
         *     参数: entity_id — 路径参数实体 id；payload — 更新载荷；session — 请求级会话。
         *     返回值: EntityRead（更新后）。异常: 404/422 由全局异常处理器统一出口。
         *     依赖: app.entities.service。
         */
        patch: operations["update_entity_api_entities__entity_id__patch"];
        trace?: never;
    };
    "/api/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Relations
         * @description 条件查询关系（GET /api/relations?source=&target=&type=，无参返回全量）。
         *
         *     作用: 参数解析 + 调用 service；按端点/类型过滤关系。
         *     参数: source/target — 端点实体 id（可选）；type — 关系类型（可选）；
         *         session — 请求级会话。
         *     返回值: list[RelationRead]。异常: 由全局异常处理器统一出口。
         *     依赖: app.relations.service。
         */
        get: operations["search_relations_api_relations_get"];
        put?: never;
        /**
         * Create Relation
         * @description 创建关系（POST /api/relations）。
         *
         *     作用: 参数解析 + 调用 service；id 由系统生成并随响应返回。
         *     参数: payload — 创建载荷；session — 请求级数据库会话（依赖注入）。
         *     返回值: RelationRead（201）。异常: 404/409/422 由全局异常处理器统一出口。
         *     依赖: app.relations.service。
         */
        post: operations["create_relation_api_relations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relations/{relation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Relation
         * @description 查询关系详情（GET /api/relations/{id}）。
         *
         *     作用: 参数解析 + 调用 service。
         *     参数: relation_id — 路径参数关系 id；session — 请求级会话。
         *     返回值: RelationRead。异常: 404 由全局异常处理器统一出口。
         *     依赖: app.relations.service。
         */
        get: operations["get_relation_api_relations__relation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Relation
         * @description 删除关系（DELETE /api/relations/{id}；删除即解除对两端实体的引用）。
         *
         *     作用: 参数解析 + 调用 service。
         *     参数: relation_id — 路径参数关系 id；session — 请求级会话。
         *     返回值: 无（204）。异常: 404 由全局异常处理器统一出口。
         *     依赖: app.relations.service。
         */
        delete: operations["delete_relation_api_relations__relation_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Relation
         * @description 局部更新关系动态属性（PATCH /api/relations/{id}；端点与 id/type 不可变）。
         *
         *     作用: 参数解析 + 调用 service；仅更新显式提供的动态字段。
         *     参数: relation_id — 路径参数关系 id；payload — 更新载荷；session — 请求级会话。
         *     返回值: RelationRead（更新后）。异常: 404/422 由全局异常处理器统一出口。
         *     依赖: app.relations.service。
         */
        patch: operations["update_relation_api_relations__relation_id__patch"];
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph
         * @description 三视角过滤图查询（GET /api/graph?perspective=author|character|audience）。
         *
         *     作用: 参数解析 + 调用 service；过滤规则与可见性判定全部在 service 层。
         *     参数: perspective — 视角枚举（必填）；character_id — character 视角角色 id；
         *         session — 请求级数据库会话（依赖注入）。
         *     返回值: GraphData（nodes+edges）。异常: 403/422 由全局异常处理器统一出口。
         *     依赖: app.perspectives.service。
         */
        get: operations["get_graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * EntityBrief
         * @description 实体摘要响应（@ 检索列表，供前端选择器）。
         *
         *     audience_known 供选择器提示「实体对当前视角是否可见」（F07，判定基准
         *     为前端已加载图数据的节点集合，audience 视角下未收录实体不可见）。
         */
        EntityBrief: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "character" | "faction" | "location" | "item" | "skill" | "event" | "concept";
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
            /** Audience Known */
            audience_known: boolean;
        };
        /**
         * EntityCreate
         * @description 创建实体请求体。
         *
         *     作用: POST /api/entities 的载荷模型；extra=forbid 拒绝未知字段（含 id——
         *     id 由系统生成，禁止客户端指定）。
         *     参数: 无（字段见 EntityBase）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        EntityCreate: {
            /**
             * Type
             * @enum {string}
             */
            type: "character" | "faction" | "location" | "item" | "skill" | "event" | "concept";
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Audience Known
             * @default false
             */
            audience_known: boolean;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /**
         * EntityRead
         * @description 实体完整响应（详情/创建/更新返回）。
         */
        EntityRead: {
            /**
             * Type
             * @enum {string}
             */
            type: "character" | "faction" | "location" | "item" | "skill" | "event" | "concept";
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Audience Known
             * @default false
             */
            audience_known: boolean;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EntityUpdate
         * @description 局部更新实体请求体（PATCH）。
         *
         *     作用:
         *         所有字段可选，仅更新显式提供的字段；extra=forbid 保证 id 不可变
         *         （传入 id 字段直接被 422 拒绝，见 entities/CONSTRAINTS.md）。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        EntityUpdate: {
            /** Name */
            name?: string | null;
            /** Aliases */
            aliases?: string[] | null;
            /** Description */
            description?: string | null;
            /** Audience Known */
            audience_known?: boolean | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * GraphData
         * @description 三视角过滤图查询响应（GET /api/graph）。
         *
         *     作用: 过滤后的 nodes+edges 集合，供前端 G6 渲染。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        GraphData: {
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][];
            /** Edges */
            edges?: components["schemas"]["GraphEdge"][];
        };
        /**
         * GraphEdge
         * @description 图边投影（关系轻量摘要，仅 id 四元组——不含任何名称字段，被过滤实体名不可能经边泄露）。
         *
         *     作用: 图可视化边数据。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        GraphEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
        };
        /**
         * GraphNode
         * @description 图节点投影（实体轻量摘要）。
         *
         *     作用: 图可视化节点数据；仅含渲染必需字段，不含 properties/description
         *         （收窄 character 视角的信息泄露通道，perspectives/CONSTRAINTS.md）。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        GraphNode: {
            /** Id */
            id: string;
            /**
             * Type
             * @description 实体类型（character/faction/location/item/skill/event/concept）
             */
            type: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RelationCreate
         * @description 创建关系请求体（POST /api/relations）。
         *
         *     作用:
         *         创建载荷模型；extra=forbid 拒绝未知字段（含 id——id 由系统生成，
         *         禁止客户端指定）。端点/known_by 的数据库级校验在 service 层。
         *     参数: 无（字段定义见下，蓝图见 docs/data_struct_define.md §2）。
         *     返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        RelationCreate: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /** Trust */
            trust?: number | null;
            /** Intimacy */
            intimacy?: number | null;
            /** Dependency */
            dependency?: number | null;
            /** Resentment */
            resentment?: number | null;
            /** Public Identity */
            public_identity?: string | null;
            /** Private Identity */
            private_identity?: string | null;
            /** Promise */
            promise?: string | null;
            /** Wants From */
            wants_from?: string | null;
            /** Believes Other Wants */
            believes_other_wants?: string | null;
            /** Leverage */
            leverage?: string | null;
            /** Boundary */
            boundary?: string | null;
            /** Status */
            status?: string | null;
            /** Known By */
            known_by?: string[];
            /**
             * Audience Known
             * @default false
             */
            audience_known: boolean;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /**
         * RelationRead
         * @description 关系完整响应（详情/创建/更新/列表返回）。
         *
         *     作用: 对外只读 DTO；字段与 ORM 模型一致（from_attributes 装配）。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        RelationRead: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /** Trust */
            trust: number | null;
            /** Intimacy */
            intimacy: number | null;
            /** Dependency */
            dependency: number | null;
            /** Resentment */
            resentment: number | null;
            /** Public Identity */
            public_identity: string | null;
            /** Private Identity */
            private_identity: string | null;
            /** Promise */
            promise: string | null;
            /** Wants From */
            wants_from: string | null;
            /** Believes Other Wants */
            believes_other_wants: string | null;
            /** Leverage */
            leverage: string | null;
            /** Boundary */
            boundary: string | null;
            /** Status */
            status: string | null;
            /** Known By */
            known_by: string[];
            /** Audience Known */
            audience_known: boolean;
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RelationUpdate
         * @description 局部更新关系请求体（PATCH）。
         *
         *     作用:
         *         动态属性全部可选，仅更新显式提供的字段；extra=forbid 保证
         *         id/source/target/type 不可变（传入即被 422 拒绝，见 relations/CONSTRAINTS.md）。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        RelationUpdate: {
            /** Trust */
            trust?: number | null;
            /** Intimacy */
            intimacy?: number | null;
            /** Dependency */
            dependency?: number | null;
            /** Resentment */
            resentment?: number | null;
            /** Public Identity */
            public_identity?: string | null;
            /** Private Identity */
            private_identity?: string | null;
            /** Promise */
            promise?: string | null;
            /** Wants From */
            wants_from?: string | null;
            /** Believes Other Wants */
            believes_other_wants?: string | null;
            /** Leverage */
            leverage?: string | null;
            /** Boundary */
            boundary?: string | null;
            /** Status */
            status?: string | null;
            /** Known By */
            known_by?: string[] | null;
            /** Audience Known */
            audience_known?: boolean | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    search_entities_api_entities_get: {
        parameters: {
            query?: {
                q?: string;
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityBrief"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entity_api_entities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_api_entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entity_api_entities__entity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entity_api_entities__entity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_relations_api_relations_get: {
        parameters: {
            query?: {
                source?: string | null;
                target?: string | null;
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_relation_api_relations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_relation_api_relations__relation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_relation_api_relations__relation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_relation_api_relations__relation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_graph_get: {
        parameters: {
            query: {
                /** @description 视角：author 全知 / character 角色 / audience 观众 */
                perspective: "author" | "character" | "audience";
                /** @description character 视角必填：视角角色的实体 id */
                character_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
