/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查端点（存活探针，供测试与运维验证服务可用）。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Entities
         * @description 检索实体（GET /api/entities?q=&type=&project_id=，@ 实体选择器数据源）。
         *
         *     作用: 参数解析 + 调用 service；q 匹配名称/别名，type 过滤类型，
         *         project_id 过滤项目归属（F11 多项目；缺省=全库）。
         *     参数: q — 关键字（空返回全量）；type — 实体类型（可选）；
         *         project_id — 项目 id（可选）；session — 请求级会话。
         *     返回值: list[EntityBrief]。异常: 由全局异常处理器统一出口。
         *     依赖: app.entities.service。
         */
        get: operations["search_entities_api_entities_get"];
        put?: never;
        /**
         * Create Entity
         * @description 创建实体（POST /api/entities）。
         *
         *     作用: 参数解析 + 调用 service；id 由系统生成并随响应返回。
         *     参数: payload — 创建载荷；session — 请求级数据库会话（依赖注入）。
         *     返回值: EntityRead（201）。异常: 由全局异常处理器统一出口。
         *     依赖: app.entities.service。
         */
        post: operations["create_entity_api_entities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity
         * @description 查询实体详情（GET /api/entities/{id}）。
         *
         *     作用: 参数解析 + 调用 service。
         *     参数: entity_id — 路径参数实体 id；session — 请求级数据库会话。
         *     返回值: EntityRead。异常: 404 由全局异常处理器统一出口。
         *     依赖: app.entities.service。
         */
        get: operations["get_entity_api_entities__entity_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Entity
         * @description 删除实体（DELETE /api/entities/{id}；被引用时 409 阻断）。
         *
         *     作用: 参数解析 + 调用 service。
         *     参数: entity_id — 路径参数实体 id；session — 请求级数据库会话。
         *     返回值: 无（204）。异常: 404/409 由全局异常处理器统一出口。
         *     依赖: app.entities.service。
         */
        delete: operations["delete_entity_api_entities__entity_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Entity
         * @description 局部更新实体（PATCH /api/entities/{id}；id 不可变）。
         *
         *     作用: 参数解析 + 调用 service；仅更新显式提供的字段。
         *     参数: entity_id — 路径参数实体 id；payload — 更新载荷；session — 请求级会话。
         *     返回值: EntityRead（更新后）。异常: 404/422 由全局异常处理器统一出口。
         *     依赖: app.entities.service。
         */
        patch: operations["update_entity_api_entities__entity_id__patch"];
        trace?: never;
    };
    "/api/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Relations
         * @description 条件查询关系（GET /api/relations?source=&target=&type=&project_id=，无参返回全量）。
         *
         *     作用: 参数解析 + 调用 service；按端点/类型/项目过滤关系。
         *     参数: source/target — 端点实体 id（可选）；type — 关系类型（可选）；
         *         project_id — 项目 id（可选，F11 多项目）；session — 请求级会话。
         *     返回值: list[RelationRead]。异常: 由全局异常处理器统一出口。
         *     依赖: app.relations.service。
         */
        get: operations["search_relations_api_relations_get"];
        put?: never;
        /**
         * Create Relation
         * @description 创建关系（POST /api/relations）。
         *
         *     作用: 参数解析 + 调用 service；id 由系统生成并随响应返回。
         *     参数: payload — 创建载荷；session — 请求级数据库会话（依赖注入）。
         *     返回值: RelationRead（201）。异常: 404/409/422 由全局异常处理器统一出口。
         *     依赖: app.relations.service。
         */
        post: operations["create_relation_api_relations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relations/{relation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Relation
         * @description 查询关系详情（GET /api/relations/{id}）。
         *
         *     作用: 参数解析 + 调用 service。
         *     参数: relation_id — 路径参数关系 id；session — 请求级会话。
         *     返回值: RelationRead。异常: 404 由全局异常处理器统一出口。
         *     依赖: app.relations.service。
         */
        get: operations["get_relation_api_relations__relation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Relation
         * @description 删除关系（DELETE /api/relations/{id}；删除即解除对两端实体的引用）。
         *
         *     作用: 参数解析 + 调用 service。
         *     参数: relation_id — 路径参数关系 id；session — 请求级会话。
         *     返回值: 无（204）。异常: 404 由全局异常处理器统一出口。
         *     依赖: app.relations.service。
         */
        delete: operations["delete_relation_api_relations__relation_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Relation
         * @description 局部更新关系动态属性（PATCH /api/relations/{id}；端点与 id/type 不可变）。
         *
         *     作用: 参数解析 + 调用 service；仅更新显式提供的动态字段。
         *     参数: relation_id — 路径参数关系 id；payload — 更新载荷；session — 请求级会话。
         *     返回值: RelationRead（更新后）。异常: 404/422 由全局异常处理器统一出口。
         *     依赖: app.relations.service。
         */
        patch: operations["update_relation_api_relations__relation_id__patch"];
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph
         * @description 三视角 × 项目维度过滤图查询（GET /api/graph?perspective=...&project_id=...）。
         *
         *     作用: 参数解析 + 调用 service；过滤规则与可见性判定全部在 service 层。
         *     参数: perspective — 视角枚举（必填）；character_id — character 视角角色 id；
         *         project_id — 项目 id（缺省=默认项目）；session — 请求级数据库会话。
         *     返回值: GraphData（nodes+edges）。异常: 403/404/422 由全局异常处理器统一出口。
         *     依赖: app.perspectives.service。
         */
        get: operations["get_graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Images
         * @description 图片明细列表（按归属）。
         *
         *     作用: 实体详情面板图片区/通用资产编辑表单的数据源路由。
         *     参数: scope — 'general' | 'entity'（Literal 校验）；owner_id — 归属 id；
         *         session — 资产库会话。
         *     返回值: list[AssetImageRead]。异常: ValidationError（422 scope 非法）。
         *     依赖: app.assets.service.list_images。
         */
        get: operations["list_images_api_assets_images_get"];
        put?: never;
        /**
         * Upload Image
         * @description 上传图片（multipart：file + scope + owner_id）。
         *
         *     作用: 图片上传路由——multipart 表单解析后委托 service（校验/写盘/入库）。
         *     参数: file — 图片文件；scope — 'general' | 'entity'；owner_id — 归属 id；
         *         session — 资产库会话；main_session — 主库会话。
         *     返回值: AssetImageRead（含静态访问 url）。
         *     异常: NotFoundError（404 归属不存在）/ ValidationError（422 类型或超限）。
         *     依赖: app.assets.service.upload_image、双会话依赖。
         */
        post: operations["upload_image_api_assets_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/file/{stored_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Image File
         * @description 图片文件访问（/api 同源路由，HTML 资产页内图片引用走此地址）。
         *
         *     作用: 以 FileResponse 返回图片字节（mime 按扩展名推断）；路径穿越由
         *         storage.resolve_stored_path 防线拦截。
         *     参数: stored_name — 存储名；session — 资产库会话。返回值: FileResponse。
         *     异常: NotFoundError（404 文件不存在）/ ValidationError（422 路径非法）。
         *     依赖: app.assets.service.get_image_file。
         */
        get: operations["get_image_file_api_assets_file__stored_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Image
         * @description 删除图片（记录 + 物理文件 + 封面引用清理）。
         *
         *     作用: 图片删除路由。
         *     参数: image_id — 图片 id；session — 资产库会话。返回值: 无（204）。
         *     异常: NotFoundError（404）。
         *     依赖: app.assets.service.delete_image。
         */
        delete: operations["delete_image_api_assets_images__image_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/general": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List General
         * @description 通用资产卡片列表（可按分类过滤）。
         *
         *     作用: 通用资产区数据源路由。
         *     参数: category — 分类过滤（可空）；session — 资产库会话。
         *     返回值: list[AssetCard]。异常: 无。
         *     依赖: app.assets.service.list_general。
         */
        get: operations["list_general_api_assets_general_get"];
        put?: never;
        /**
         * Create General
         * @description 创建通用资产。
         *
         *     作用: 通用资产创建路由。
         *     参数: payload — 创建载荷；session — 资产库会话。返回值: AssetRead。
         *     异常: ValidationError（422 字段校验）。
         *     依赖: app.assets.service.create_general。
         */
        post: operations["create_general_api_assets_general_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/general/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get General
         * @description 通用资产详情（含图片明细）。
         *
         *     作用: 编辑表单数据源路由（列表仅有摘要）。
         *     参数: asset_id — 资产 id；session — 资产库会话。返回值: AssetRead。
         *     异常: NotFoundError（404）。
         *     依赖: app.assets.service.get_general。
         */
        get: operations["get_general_api_assets_general__asset_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete General
         * @description 删除通用资产（级联清理图片与文件）。
         *
         *     作用: 通用资产删除路由。
         *     参数: asset_id — 资产 id；session — 资产库会话。返回值: 无（204）。
         *     异常: NotFoundError（404）。
         *     依赖: app.assets.service.delete_general。
         */
        delete: operations["delete_general_api_assets_general__asset_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update General
         * @description 局部更新通用资产。
         *
         *     作用: 通用资产编辑路由。
         *     参数: asset_id — 资产 id；payload — 更新载荷；session — 资产库会话。
         *     返回值: AssetRead。异常: NotFoundError（404）。
         *     依赖: app.assets.service.update_general。
         */
        patch: operations["update_general_api_assets_general__asset_id__patch"];
        trace?: never;
    };
    "/api/assets/general/{asset_id}/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get General Page
         * @description 通用资产 HTML 页（内嵌查看器数据源）。
         *
         *     作用: 返回存储的自包含 HTML 全文（text/html）。
         *     参数: asset_id — 资产 id；session — 资产库会话。返回值: HTMLResponse。
         *     异常: NotFoundError（404）。
         *     依赖: app.assets.service.get_general_page。
         */
        get: operations["get_general_page_api_assets_general__asset_id__page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/general/{asset_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Cover
         * @description 设置通用资产封面。
         *
         *     作用: 卡片缩略图人工指定路由。
         *     参数: asset_id — 资产 id；body — 含 image_id；session — 资产库会话。
         *     返回值: AssetRead。异常: NotFoundError / ValidationError（归属不符）。
         *     依赖: app.assets.service.set_cover。
         */
        put: operations["set_cover_api_assets_general__asset_id__cover_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entity Cards
         * @description 项目资产卡片列表（主库实体按类型分组；含孤儿清扫）。
         *
         *     作用: 项目资产区数据源路由；project_id 过滤项目归属（F11 多项目）。
         *     参数: project_id — 项目 id（可选）；session — 资产库会话；main_session — 主库会话。
         *     返回值: list[EntityAssetCard]（类型序 + 名称序）。异常: 404 项目不存在。
         *     依赖: app.assets.service.list_entity_cards。
         */
        get: operations["list_entity_cards_api_assets_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/entity/{entity_id}/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity Page
         * @description 实体资产 HTML 页（惰性生成/过期再生）。
         *
         *     作用: 项目资产内嵌查看器数据源路由。
         *     参数: entity_id — 实体 id；session — 资产库会话；main_session — 主库会话。
         *     返回值: HTMLResponse。异常: NotFoundError（404 实体不存在）。
         *     依赖: app.assets.service.get_entity_page。
         */
        get: operations["get_entity_page_api_assets_entity__entity_id__page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description 列出全部项目（GET /api/projects，按最近活跃倒序）。
         *
         *     作用: 项目首屏与顶栏切换器数据源。
         *     参数: session — 请求级数据库会话。
         *     返回值: list[ProjectRead]。异常: 无。
         *     依赖: app.projects.service。
         */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description 创建项目（POST /api/projects）。
         *
         *     作用: 参数解析 + 调用 service；id 由系统生成并随响应返回。
         *     参数: payload — 创建载荷；session — 请求级数据库会话（依赖注入）。
         *     返回值: ProjectRead（201）。异常: 422 由全局异常处理器统一出口。
         *     依赖: app.projects.service。
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description 查询项目详情（GET /api/projects/{id}）。
         *
         *     作用: 参数解析 + 调用 service。
         *     参数: project_id — 路径参数项目 id；session — 请求级数据库会话。
         *     返回值: ProjectRead。异常: 404 由全局异常处理器统一出口。
         *     依赖: app.projects.service。
         */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description 删除项目并级联清理（DELETE /api/projects/{id}）。
         *
         *     作用:
         *         跨模块级联编排（组合层，见模块 docstring）：校验 → 删该项目全部关系
         *         → 删该项目全部实体（收集实体 id）→ 删项目行并原子提交主库 →
         *         按实体 id 集合显式清扫资产库（记录 + 图片 + 物理文件）。
         *     参数:
         *         project_id — 路径参数项目 id；session — 主库会话；
         *         asset_session — 资产库会话（独立事务）。
         *     返回值: 无（204）。
         *     异常: 404（项目不存在）/ 422（默认项目受保护）由全局异常处理器统一出口；
         *         主库删除原子提交，资产清扫失败由读取时孤儿清扫兜底。
         *     依赖: app.projects.service、app.relations.service、app.entities.service、
         *         app.assets.service、app.agent.service（F10：会话与记忆文档清理）。
         */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Project
         * @description 局部更新项目（PATCH /api/projects/{id}；id 与计数器不可变）。
         *
         *     作用: 参数解析 + 调用 service；改名 / 描述更新。
         *     参数: project_id — 路径参数项目 id；payload — 更新载荷；session — 请求级会话。
         *     返回值: ProjectRead（更新后）。异常: 404/422 由全局异常处理器统一出口。
         *     依赖: app.projects.service。
         */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/agent/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description 列出项目会话（最近活跃在前；缺省归属默认项目）。
         */
        get: operations["list_sessions_api_agent_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description 创建会话（201；项目维度归属校验经 projects.service）。
         */
        post: operations["create_session_api_agent_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/sessions/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Session Messages
         * @description 读取会话全部消息（时间正序；会话不存在 404）。
         */
        get: operations["list_session_messages_api_agent_sessions__conversation_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description SSE 流式对话（事件协议见 agent/ARCHITECTURE.md；会话不存在 404）。
         */
        post: operations["chat_api_agent_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose
         * @description 生成实体/关系写入草案（LLM JSON mode；不落库）。
         */
        post: operations["propose_api_agent_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm
         * @description 确认草案并落库（两段式第二段；服务端复核全部 payload）。
         */
        post: operations["confirm_api_agent_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/memory-docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Memory Docs
         * @description 列出项目记忆文档卡片（名称+更新时间+首段预览）。
         */
        get: operations["list_memory_docs_api_agent_memory_docs_get"];
        put?: never;
        /**
         * Create Memory Doc
         * @description 按模板创建记忆文档（kind ∈ positioning/style，缺省 positioning；201）。
         */
        post: operations["create_memory_doc_api_agent_memory_docs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/memory-docs/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Memory Doc
         * @description 读取记忆文档全文（含段列表与段版本）。
         */
        get: operations["get_memory_doc_api_agent_memory_docs__doc_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Memory Doc
         * @description 删除记忆文档（段经级联清理；204）。
         */
        delete: operations["delete_memory_doc_api_agent_memory_docs__doc_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/memory-docs/{doc_id}/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Memory Doc Page
         * @description 记忆文档自包含 HTML 页（iframe 预览数据源；全转义）。
         */
        get: operations["get_memory_doc_page_api_agent_memory_docs__doc_id__page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/memory-docs/{doc_id}/sections/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Memory Doc Section
         * @description 段级更新（CAS 乐观锁：expected_version 不符 409；用户手改优先）。
         */
        patch: operations["update_memory_doc_section_api_agent_memory_docs__doc_id__sections__section_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetCard
         * @description 通用资产卡片（列表项：缩略图 + 摘要，不含 html 全文与图片明细）。
         */
        AssetCard: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Cover Url */
            cover_url: string | null;
            /** Image Count */
            image_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AssetImageRead
         * @description 图片元数据响应（url 为静态访问地址）。
         */
        AssetImageRead: {
            /** Id */
            id: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "general" | "entity";
            /** Owner Id */
            owner_id: string;
            /** Filename Orig */
            filename_orig: string;
            /** Stored Name */
            stored_name: string;
            /** Mime */
            mime: string;
            /** Size */
            size: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Url
             * @description 图片访问地址（/api 前缀同源路由——HTML 资产页内的图片引用在任何部署
             *     形态下都与页面同源，开发期经 vite /api 代理，生产可经网关统一转发）。
             */
            readonly url: string;
        };
        /**
         * AssetRead
         * @description 通用资产完整响应（详情/创建/更新返回，含图片列表）。
         */
        AssetRead: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "general" | "entity";
            /** Category */
            category: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Cover Image Id */
            cover_image_id: string | null;
            /** Cover Url */
            cover_url: string | null;
            /** Images */
            images: components["schemas"]["AssetImageRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Body_upload_image_api_assets_images_post */
        Body_upload_image_api_assets_images_post: {
            /** File */
            file: string;
            /** Scope */
            scope: string;
            /** Owner Id */
            owner_id: string;
        };
        /**
         * ChatRequest
         * @description 对话请求（SSE 流式响应）。
         *
         *     参数: conversation_id — 会话 id；message — 用户输入；
         *         perspective — 上下文视角（图谱数据经该视角过滤后注入）；
         *         character_id — character 视角的角色 id。
         */
        ChatRequest: {
            /** Conversation Id */
            conversation_id: string;
            /** Message */
            message: string;
            /**
             * Perspective
             * @default author
             * @enum {string}
             */
            perspective: "author" | "character" | "audience";
            /**
             * Character Id
             * @default
             */
            character_id: string;
        };
        /**
         * ConfirmFailedItem
         * @description 确认结果：失败项（含三要素 reason）。
         */
        ConfirmFailedItem: {
            /** Draft Id */
            draft_id: string;
            /** Reason */
            reason: string;
        };
        /**
         * ConfirmItem
         * @description 确认请求的单项（confirmed=False 表示放弃该条）。
         */
        ConfirmItem: {
            /** Draft Id */
            draft_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "entity" | "relation";
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Confirmed */
            confirmed: boolean;
        };
        /**
         * ConfirmRequest
         * @description 确认写入请求（无状态回传草案，服务端重新校验全部 payload）。
         */
        ConfirmRequest: {
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /** Items */
            items: components["schemas"]["ConfirmItem"][];
        };
        /**
         * ConfirmResponse
         * @description 确认写入响应。
         */
        ConfirmResponse: {
            /** Created */
            created?: components["schemas"]["ConfirmResultItem"][];
            /** Failed */
            failed?: components["schemas"]["ConfirmFailedItem"][];
        };
        /**
         * ConfirmResultItem
         * @description 确认结果：成功项（写入后的实体/关系 id 与名称）。
         */
        ConfirmResultItem: {
            /** Draft Id */
            draft_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "entity" | "relation";
            /** Target Id */
            target_id: string;
            /** Name */
            name: string;
        };
        /**
         * CoverSet
         * @description 设置封面请求体（PUT /general/{id}/cover）。
         */
        CoverSet: {
            /** Image Id */
            image_id: string;
        };
        /**
         * DraftItem
         * @description 单条写入草案（propose 产出；confirm 原样回传 payload）。
         */
        DraftItem: {
            /** Draft Id */
            draft_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "entity" | "relation";
            /**
             * Payload
             * @description entities/relations service 输入形状的宽松载荷
             */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Summary
             * @description 给作者看的一句话摘要
             */
            summary: string;
        };
        /**
         * EntityAssetCard
         * @description 项目资产卡片（主库实体的展示面：缩略图 + 名称/概述）。
         */
        EntityAssetCard: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Cover Url */
            cover_url: string | null;
            /** Image Count */
            image_count: number;
        };
        /**
         * EntityBrief
         * @description 实体摘要响应（@ 检索列表，供前端选择器）。
         *
         *     audience_known 供选择器提示「实体对当前视角是否可见」（F07，判定基准
         *     为前端已加载图数据的节点集合，audience 视角下未收录实体不可见）。
         */
        EntityBrief: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "character" | "faction" | "location" | "item" | "skill" | "event" | "concept";
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
            /** Audience Known */
            audience_known: boolean;
        };
        /**
         * EntityCreate
         * @description 创建实体请求体。
         *
         *     作用: POST /api/entities 的载荷模型；extra=forbid 拒绝未知字段（含 id——
         *     id 由系统生成，禁止客户端指定）。project_id 可选——缺省归属默认项目
         *     （F11 渐进迁移：不带 project_id 的旧客户端行为不变）。
         *     参数: 无（字段见 EntityBase + project_id）。返回值: 无（模型类）。
         *     异常: 无。依赖: pydantic。
         */
        EntityCreate: {
            /**
             * Type
             * @enum {string}
             */
            type: "character" | "faction" | "location" | "item" | "skill" | "event" | "concept";
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Audience Known
             * @default false
             */
            audience_known: boolean;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
            /** Project Id */
            project_id?: string | null;
        };
        /**
         * EntityRead
         * @description 实体完整响应（详情/创建/更新返回）。
         */
        EntityRead: {
            /**
             * Type
             * @enum {string}
             */
            type: "character" | "faction" | "location" | "item" | "skill" | "event" | "concept";
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Audience Known
             * @default false
             */
            audience_known: boolean;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EntityUpdate
         * @description 局部更新实体请求体（PATCH）。
         *
         *     作用:
         *         所有字段可选，仅更新显式提供的字段；extra=forbid 保证 id 不可变
         *         （传入 id 字段直接被 422 拒绝，见 entities/CONSTRAINTS.md）。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        EntityUpdate: {
            /** Name */
            name?: string | null;
            /** Aliases */
            aliases?: string[] | null;
            /** Description */
            description?: string | null;
            /** Audience Known */
            audience_known?: boolean | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * GeneralAssetCreate
         * @description 创建通用资产请求体（extra=forbid 拒绝未知字段）。
         */
        GeneralAssetCreate: {
            /**
             * Category
             * @default
             */
            category: string;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
        };
        /**
         * GeneralAssetUpdate
         * @description 局部更新通用资产请求体（仅更新显式提供的字段；extra=forbid）。
         */
        GeneralAssetUpdate: {
            /** Category */
            category?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * GraphData
         * @description 三视角过滤图查询响应（GET /api/graph）。
         *
         *     作用: 过滤后的 nodes+edges 集合，供前端 G6 渲染。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        GraphData: {
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][];
            /** Edges */
            edges?: components["schemas"]["GraphEdge"][];
        };
        /**
         * GraphEdge
         * @description 图边投影（关系轻量摘要，仅 id 四元组——不含任何名称字段，被过滤实体名不可能经边泄露）。
         *
         *     作用: 图可视化边数据。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        GraphEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
        };
        /**
         * GraphNode
         * @description 图节点投影（实体轻量摘要）。
         *
         *     作用: 图可视化节点数据；仅含渲染必需字段，不含 properties/description
         *         （收窄 character 视角的信息泄露通道，perspectives/CONSTRAINTS.md）。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        GraphNode: {
            /** Id */
            id: string;
            /**
             * Type
             * @description 实体类型（character/faction/location/item/skill/event/concept）
             */
            type: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MemoryDocBrief
         * @description 记忆文档卡片摘要（列表视图：名称+更新时间+首行摘要，DESIGN §5.4）。
         */
        MemoryDocBrief: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Version */
            version: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Preview
             * @description 首段内容预览（截断）
             */
            preview: string;
        };
        /**
         * MemoryDocRead
         * @description 记忆文档响应（含全部段，按 seq 排序）。
         */
        MemoryDocRead: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Sections */
            sections?: components["schemas"]["MemoryDocSectionRead"][];
        };
        /**
         * MemoryDocSectionRead
         * @description 文档段响应（version 为段级 CAS 令牌）。
         */
        MemoryDocSectionRead: {
            /** Id */
            id: string;
            /** Seq */
            seq: number;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Updated By
             * @enum {string}
             */
            updated_by: "user" | "agent";
            /** Version */
            version: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MessageRead
         * @description 消息响应。
         */
        MessageRead: {
            /** Id */
            id: string;
            /** Conversation Id */
            conversation_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "summary" | "tool";
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ProjectCreate
         * @description 创建项目请求体（POST /api/projects）。
         *
         *     作用: 创建载荷模型；extra=forbid 拒绝未知字段（含 id——id 由系统生成）。
         *     参数: 无（字段见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * ProjectRead
         * @description 项目完整响应（列表/详情/创建/更新返回）。
         *
         *     作用: 对外只读 DTO；计数器供项目首屏卡片（N 实体）与删除确认后果清单。
         *     参数: 无（字段见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        ProjectRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Entity Count */
            entity_count: number;
            /** Relation Count */
            relation_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectUpdate
         * @description 局部更新项目请求体（PATCH /api/projects/{id}）。
         *
         *     作用: 字段可选、仅更新显式提供项；extra=forbid 保证 id / 计数器不可
         *         由客户端指定（计数器只经领域写路径事务内维护）。
         *     参数: 无（字段见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * ProposeRequest
         * @description 生成草案请求。
         */
        ProposeRequest: {
            /** Session Id */
            session_id: string;
            /** Message */
            message: string;
            /**
             * Perspective
             * @default author
             * @enum {string}
             */
            perspective: "author" | "character" | "audience";
            /**
             * Character Id
             * @default
             */
            character_id: string;
        };
        /**
         * ProposeResponse
         * @description 草案列表响应。
         */
        ProposeResponse: {
            /** Session Id */
            session_id: string;
            /** Drafts */
            drafts?: components["schemas"]["DraftItem"][];
        };
        /**
         * RelationCreate
         * @description 创建关系请求体（POST /api/relations）。
         *
         *     作用:
         *         创建载荷模型；extra=forbid 拒绝未知字段（含 id——id 由系统生成，
         *         禁止客户端指定）。端点/known_by 的数据库级校验在 service 层。
         *     参数: 无（字段定义见下，蓝图见 docs/data_struct_define.md §2）。
         *     返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        RelationCreate: {
            /** Project Id */
            project_id?: string | null;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /** Trust */
            trust?: number | null;
            /** Intimacy */
            intimacy?: number | null;
            /** Dependency */
            dependency?: number | null;
            /** Resentment */
            resentment?: number | null;
            /** Public Identity */
            public_identity?: string | null;
            /** Private Identity */
            private_identity?: string | null;
            /** Promise */
            promise?: string | null;
            /** Wants From */
            wants_from?: string | null;
            /** Believes Other Wants */
            believes_other_wants?: string | null;
            /** Leverage */
            leverage?: string | null;
            /** Boundary */
            boundary?: string | null;
            /** Status */
            status?: string | null;
            /** Known By */
            known_by?: string[];
            /**
             * Audience Known
             * @default false
             */
            audience_known: boolean;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /**
         * RelationRead
         * @description 关系完整响应（详情/创建/更新/列表返回）。
         *
         *     作用: 对外只读 DTO；字段与 ORM 模型一致（from_attributes 装配）。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        RelationRead: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /** Trust */
            trust: number | null;
            /** Intimacy */
            intimacy: number | null;
            /** Dependency */
            dependency: number | null;
            /** Resentment */
            resentment: number | null;
            /** Public Identity */
            public_identity: string | null;
            /** Private Identity */
            private_identity: string | null;
            /** Promise */
            promise: string | null;
            /** Wants From */
            wants_from: string | null;
            /** Believes Other Wants */
            believes_other_wants: string | null;
            /** Leverage */
            leverage: string | null;
            /** Boundary */
            boundary: string | null;
            /** Status */
            status: string | null;
            /** Known By */
            known_by: string[];
            /** Audience Known */
            audience_known: boolean;
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RelationUpdate
         * @description 局部更新关系请求体（PATCH）。
         *
         *     作用:
         *         动态属性全部可选，仅更新显式提供的字段；extra=forbid 保证
         *         id/source/target/type 不可变（传入即被 422 拒绝，见 relations/CONSTRAINTS.md）。
         *     参数: 无（字段定义见下）。返回值: 无（模型类）。异常: 无。依赖: pydantic。
         */
        RelationUpdate: {
            /** Trust */
            trust?: number | null;
            /** Intimacy */
            intimacy?: number | null;
            /** Dependency */
            dependency?: number | null;
            /** Resentment */
            resentment?: number | null;
            /** Public Identity */
            public_identity?: string | null;
            /** Private Identity */
            private_identity?: string | null;
            /** Promise */
            promise?: string | null;
            /** Wants From */
            wants_from?: string | null;
            /** Believes Other Wants */
            believes_other_wants?: string | null;
            /** Leverage */
            leverage?: string | null;
            /** Boundary */
            boundary?: string | null;
            /** Status */
            status?: string | null;
            /** Known By */
            known_by?: string[] | null;
            /** Audience Known */
            audience_known?: boolean | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SectionUpdate
         * @description 段内容更新请求（用户编辑与 agent patch 确认共用；乐观锁）。
         *
         *     参数: content — 新内容；expected_version — 调用方读取时的段版本，
         *         与当前不一致即 409 冲突（用户手改优先，绝不静默覆盖）。
         */
        SectionUpdate: {
            /** Content */
            content: string;
            /** Expected Version */
            expected_version: number;
        };
        /**
         * SessionCreate
         * @description 创建会话请求。
         *
         *     参数: project_id — 归属项目（空=默认项目）；title — 会话标题（空=首条消息截断）。
         */
        SessionCreate: {
            /**
             * Project Id
             * @default
             */
            project_id: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /**
         * SessionRead
         * @description 会话响应（滚动摘要为内部字段，不外露）。
         */
        SessionRead: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    search_entities_api_entities_get: {
        parameters: {
            query?: {
                q?: string;
                type?: string | null;
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityBrief"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entity_api_entities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_api_entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entity_api_entities__entity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entity_api_entities__entity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_relations_api_relations_get: {
        parameters: {
            query?: {
                source?: string | null;
                target?: string | null;
                type?: string | null;
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_relation_api_relations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_relation_api_relations__relation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_relation_api_relations__relation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_relation_api_relations__relation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_graph_get: {
        parameters: {
            query: {
                /** @description 视角：author 全知 / character 角色 / audience 观众 */
                perspective: "author" | "character" | "audience";
                /** @description character 视角必填：视角角色的实体 id */
                character_id?: string | null;
                /** @description 项目 id（F11 多项目；缺省=默认项目） */
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_images_api_assets_images_get: {
        parameters: {
            query: {
                scope: "general" | "entity";
                owner_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetImageRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_api_assets_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_assets_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetImageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_file_api_assets_file__stored_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stored_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_api_assets_images__image_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_general_api_assets_general_get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetCard"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_general_api_assets_general_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneralAssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_general_api_assets_general__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_general_api_assets_general__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_general_api_assets_general__asset_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneralAssetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_general_page_api_assets_general__asset_id__page_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_cover_api_assets_general__asset_id__cover_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoverSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entity_cards_api_assets_entities_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityAssetCard"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_page_api_assets_entity__entity_id__page_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_agent_sessions_get: {
        parameters: {
            query?: {
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_agent_sessions_post: {
        parameters: {
            query?: {
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_session_messages_api_agent_sessions__conversation_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_agent_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_api_agent_propose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_agent_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memory_docs_api_agent_memory_docs_get: {
        parameters: {
            query?: {
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDocBrief"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_memory_doc_api_agent_memory_docs_post: {
        parameters: {
            query?: {
                kind?: string;
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDocRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_doc_api_agent_memory_docs__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDocRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_doc_api_agent_memory_docs__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_doc_page_api_agent_memory_docs__doc_id__page_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_memory_doc_section_api_agent_memory_docs__doc_id__sections__section_id__patch: {
        parameters: {
            query?: {
                updated_by?: string;
            };
            header?: never;
            path: {
                doc_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDocSectionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
