"""r2 add artifact core

Revision ID: 4da706c0d824
Revises: a8f3c1d6e2b4
Create Date: 2026-09-10 21:14:47.873805

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4da706c0d824'
down_revision: Union[str, None] = 'a8f3c1d6e2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级到本版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_revision_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_artifacts_type'), 'artifacts', ['type'], unique=False)
    op.create_table('artifact_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('block_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_blocks_artifact_id'), 'artifact_blocks', ['artifact_id'], unique=False)
    op.create_table('artifact_revisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'revision_no')
    )
    op.create_index(op.f('ix_artifact_revisions_artifact_id'), 'artifact_revisions', ['artifact_id'], unique=False)
    op.create_table('artifact_block_revisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('block_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['artifact_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['artifact_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'block_id')
    )
    op.create_index(op.f('ix_artifact_block_revisions_block_id'), 'artifact_block_revisions', ['block_id'], unique=False)
    op.create_index(op.f('ix_artifact_block_revisions_revision_id'), 'artifact_block_revisions', ['revision_id'], unique=False)
    op.create_table('artifact_dependencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('source_artifact_id', sa.String(), nullable=False),
    sa.Column('source_block_id', sa.String(), nullable=False),
    sa.Column('source_revision_id', sa.String(), nullable=False),
    sa.Column('dependent_artifact_id', sa.String(), nullable=False),
    sa.Column('dependency_type', sa.String(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dependent_artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_block_id'], ['artifact_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_revision_id'], ['artifact_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_block_id', 'source_revision_id', 'dependent_artifact_id', name='uq_artifact_dep')
    )
    op.create_index(op.f('ix_artifact_dependencies_dependent_artifact_id'), 'artifact_dependencies', ['dependent_artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_dependencies_project_id'), 'artifact_dependencies', ['project_id'], unique=False)
    op.create_index(op.f('ix_artifact_dependencies_source_artifact_id'), 'artifact_dependencies', ['source_artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_dependencies_source_block_id'), 'artifact_dependencies', ['source_block_id'], unique=False)
    op.create_index(op.f('ix_artifact_dependencies_source_revision_id'), 'artifact_dependencies', ['source_revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退到上一版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_dependencies_source_revision_id'), table_name='artifact_dependencies')
    op.drop_index(op.f('ix_artifact_dependencies_source_block_id'), table_name='artifact_dependencies')
    op.drop_index(op.f('ix_artifact_dependencies_source_artifact_id'), table_name='artifact_dependencies')
    op.drop_index(op.f('ix_artifact_dependencies_project_id'), table_name='artifact_dependencies')
    op.drop_index(op.f('ix_artifact_dependencies_dependent_artifact_id'), table_name='artifact_dependencies')
    op.drop_table('artifact_dependencies')
    op.drop_index(op.f('ix_artifact_block_revisions_revision_id'), table_name='artifact_block_revisions')
    op.drop_index(op.f('ix_artifact_block_revisions_block_id'), table_name='artifact_block_revisions')
    op.drop_table('artifact_block_revisions')
    op.drop_index(op.f('ix_artifact_revisions_artifact_id'), table_name='artifact_revisions')
    op.drop_table('artifact_revisions')
    op.drop_index(op.f('ix_artifact_blocks_artifact_id'), table_name='artifact_blocks')
    op.drop_table('artifact_blocks')
    op.drop_index(op.f('ix_artifacts_type'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
