"""v4 r2 lineage lifecycle and review

Revision ID: a5557d421f40
Revises: f4b7c8d9e0a1
Create Date: 2026-09-19 17:19:32.969233

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a5557d421f40'
down_revision: Union[str, None] = 'f4b7c8d9e0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级到本版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('origin_type', sa.String(), nullable=False),
    sa.Column('origin_id', sa.String(), nullable=False),
    sa.Column('origin_revision_ref', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('target_base_revision_ref', sa.String(), nullable=False),
    sa.Column('proposal_kind', sa.String(), nullable=False),
    sa.Column('patch_json', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('committed_ref', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('proposed','accepted','rejected','superseded')"),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_proposals_project_id'), 'change_proposals', ['project_id'], unique=False)
    op.create_table('lineage_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('upstream_type', sa.String(), nullable=False),
    sa.Column('upstream_id', sa.String(), nullable=False),
    sa.Column('upstream_revision_ref', sa.String(), nullable=False),
    sa.Column('downstream_type', sa.String(), nullable=False),
    sa.Column('downstream_id', sa.String(), nullable=False),
    sa.Column('downstream_revision_ref', sa.String(), nullable=False),
    sa.Column('dependency_type', sa.String(), nullable=False),
    sa.Column('invalidation_policy', sa.String(), nullable=False),
    sa.Column('compatibility_validator', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('stale_cause_ref', sa.String(), nullable=True),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("invalidation_policy IN ('hard_stale','review_required','timing_revalidate','compatibility_check','notice_only','none')"),
    sa.CheckConstraint("state IN ('active','stale','superseded','rebased')"),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['lineage_edges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lineage_downstream', 'lineage_edges', ['project_id', 'downstream_type', 'downstream_id'], unique=False)
    op.create_index('ix_lineage_upstream', 'lineage_edges', ['project_id', 'upstream_type', 'upstream_id'], unique=False)
    op.create_table('lineage_review_audits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineage_review_audits_project_id'), 'lineage_review_audits', ['project_id'], unique=False)
    op.create_index(op.f('ix_lineage_review_audits_subject_id'), 'lineage_review_audits', ['subject_id'], unique=False)
    op.add_column('artifacts', sa.Column('approval_status', sa.String(), sa.CheckConstraint("approval_status IN ('draft','review','approved','archived')"), server_default='draft', nullable=False))
    # Backfill only; legacy rows remain intact and runtime stops writing the old table.
    op.execute(sa.text("""
        INSERT INTO lineage_edges
            (id, project_id, upstream_type, upstream_id, upstream_revision_ref,
             downstream_type, downstream_id, downstream_revision_ref,
             dependency_type, invalidation_policy, compatibility_validator,
             state, stale_cause_ref, supersedes_id, created_at, updated_at)
        SELECT d.id, d.project_id, 'artifact_block', d.source_block_id, d.source_revision_id,
               'artifact', d.dependent_artifact_id, r.id, d.dependency_type, 'hard_stale', NULL,
               CASE WHEN d.is_stale THEN 'stale' ELSE 'active' END,
               CASE WHEN d.is_stale THEN d.source_revision_id ELSE NULL END,
               NULL, d.created_at, d.updated_at
        FROM artifact_dependencies d
        JOIN artifacts a ON a.id = d.dependent_artifact_id
        JOIN artifact_revisions r ON r.artifact_id = a.id AND r.revision_no = a.current_revision_no
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("V4-R2 retains immutable review/revision history; restore a pre-upgrade backup instead")
