"""F02 create entities and relationships tables

Revision ID: e9a2e0f0a667
Revises: 
Create Date: 2026-08-27 11:16:36.192813

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e9a2e0f0a667'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级到本版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('audience_known', sa.Boolean(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('trust', sa.Float(), nullable=True),
    sa.Column('intimacy', sa.Float(), nullable=True),
    sa.Column('dependency', sa.Float(), nullable=True),
    sa.Column('resentment', sa.Float(), nullable=True),
    sa.Column('public_identity', sa.String(), nullable=True),
    sa.Column('private_identity', sa.String(), nullable=True),
    sa.Column('promise', sa.String(), nullable=True),
    sa.Column('wants_from', sa.String(), nullable=True),
    sa.Column('believes_other_wants', sa.String(), nullable=True),
    sa.Column('leverage', sa.String(), nullable=True),
    sa.Column('boundary', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('known_by', sa.JSON(), nullable=False),
    sa.Column('audience_known', sa.Boolean(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target'], ['entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_source'), 'relationships', ['source'], unique=False)
    op.create_index(op.f('ix_relationships_target'), 'relationships', ['target'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回退到上一版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_target'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
